[project]
name = "ustplayer"
version = "1.0.0"
description = "中文的、面向 UTAU/UST 工程文件的可视化播放器（PySide6 + Fluent Design）"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pyside6>=6.5.0",
    "pyside6-fluent-widgets[full]>=1.11.2",
]

[project.scripts]
ustplayer = "ustplayer.app:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
