blank_issues_enabled: true
contact_links:
  - name: 📺 配布视频 / 使用教程
    url: https://www.bilibili.com/video/BV1YjcwzVEcX
    about: 如有使用问题，可先查看B站配布视频下的评论区。
  - name: 📋 更新日志
    url: https://github.com/SYEternalR/ustPlayer/releases
    about: 请先确认你使用的是最新版本。
